kind: Deployment
apiVersion: apps/v1
metadata:
  name: demowebapp
  namespace: demo-ns
  labels:
    app.kubernetes.io/name: demowebapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: demowebapp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: demowebapp
    spec:
     containers:
       - name: demowebapp
         image: 908027399517.dkr.ecr.ap-south-1.amazonaws.comdemoappimage:24
         imagePullPolicy: IfNotPresent
         ports:
           - containerPort: 8080
         livenessProbe:
           exec:
             command:
               - /bin/sh
               - -c
               - /opt/jboss/wildfly/bin/jboss-cli.sh --connect --commands='ls' | grep 'server-state=running'
           initialDelaySeconds: 60
           timeoutSeconds:  5
           failureThreshold:   5
         readinessProbe:
           httpGet:
              path: /
              port: 8080
           initialDelaySeconds: 30
           timeoutSeconds:  5
           failureThreshold:   5
         resources:
            limits: {}
            requests:
              cpu: 100m
              memory: 128Mi
         volumeMounts:
         - name: mylogpv
           mountPath: "/opt/jboss/wildfly/standalone/log"
         - name: testconfigmap
           mountPath: "/tmp/config"
     volumes:
     - name: testconfigmap
       configMap:
         name: demowebapp
         items:
         - key: sample.conf
           path: sample.conf
     - name: mylogpv
       persistentVolumeClaim:
         claimName: mylogvolclaim
     imagePullSecrets:
      - name: awsecr-cred
