apiVersion: v1
kind: PersistentVolume
metadata:
  name: mylogvol
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  awsElasticBlockStore:
    volumeID: vol-07c6da4486e807418
    fsType: ext4
