apiVersion: v1
kind: PersistentVolume
metadata:
  name: mylogvol
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  awsElasticBlockStore:
    volumeID: vol-0163dfe6cd3d7fda9
    fsType: ext4
